SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON(GRADE = GRADE_CODE)
JOIN TB_AREA ON (AREA_CODE = AREA_CODE)
WHERE AREA_CODE = (
	SELECT AREA_CODE FROM TB_MEMBER
	WHERE 이름 = '김영희'
)
ORDER BY 이름 DESC;

-- 1. 서브 쿼리의 별칭인 이름이 메인 쿼리에 있기때문에 사용 불가능
-- 2. TB_AREA 테이블 JOIN할 때 두 테이블의 컬럼명이 동일하므로 ON 대신 USING(컬럼명)을 사용 
-- 3. 비교 대상인 김영희를 조회 결과에서 제외
-- 4. 조회 결과를 이름 오름차순 조회 -> ASC	


SELECT AREA_NAME 지역명, MEMBER_ID 아이디, MEMBER_NAME 이름, GRADE_NAME 등급명
FROM TB_MEMBER
JOIN TB_GRADE ON (GRADE_CODE = GRADE)
JOIN TB_AREA USING (AREA_CODE)
WHERE AREA_CODE = (
	SELECT AREA_CODE FROM TB_MEMBER
	WHERE MEMBER_NAME = '김영희'
)AND MEMBER_NAME != '김영희'
ORDER BY 이름 ASC;

SELECT *
FROM TB_MEMBER
JOIN TB_GRADE ON (GRADE_CODE = GRADE)
JOIN TB_AREA USING (AREA_CODE)
