SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT;


SELECT DEPARTMENT_NAME||' 의 정원은 '|| CAPACITY || '명 입니다' "학과별 정원"
FROM TB_DEPARTMENT;


SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,8,1) = '2' AND ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001'; 


SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');


SELECT DEPARTMENT_NAME "학과", CATEGORY "계열"
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;


SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;


SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE 
	EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002'
	AND INSTR(STUDENT_ADDRESS, '전주시') != '0'
	AND ABSENCE_YN = 'N'
ORDER BY ENTRANCE_DATE DESC;
	

SELECT STUDENT_NO"학번", STUDENT_NAME"이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;


SELECT PROFESSOR_NAME "교수이름", EXTRACT(YEAR FROM CURRENT_DATE) - 1900 - SUBSTR(PROFESSOR_SSN,1,2) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1';


SELECT SUBSTR(PROFESSOR_NAME, 2) "이름"
FROM TB_PROFESSOR;


SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';


SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE SUBSTR(EXTRACT(YEAR FROM TB_STUDENT.ENTRANCE_DATE),1,2)  - SUBSTR(STUDENT_SSN,1,2) = '19';






SELECT STUDENT_NAME "이름", STUDENT_ADDRESS "주소"
FROM TB_STUDENT
ORDER BY "이름" ASC;

SELECT STUDENT_NAME "이름", STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;

SELECT STUDENT_NAME "학생 이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
AND SUBSTR(STUDENT_NO,1,1) = '9'
ORDER BY STUDENT_NAME ASC;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY SUBSTR(PROFESSOR_SSN, 1, 2) ASC;

SELECT


















