SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT;


SELECT DEPARTMENT_NAME||' 의 정원은 '|| CAPACITY || '명 입니다' "학과별 정원"
FROM TB_DEPARTMENT;


SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,8,1) = '2' AND ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001'; 


SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');


SELECT DEPARTMENT_NAME "학과", CATEGORY "계열"
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;


SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;


SELECT STUDENT_NO,STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE 
	EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002'
	AND INSTR(STUDENT_ADDRESS, '전주시') != '0'
	AND ABSENCE_YN = 'N'
ORDER BY ENTRANCE_DATE DESC;
	

SELECT STUDENT_NO"학번", STUDENT_NAME"이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;


SELECT PROFESSOR_NAME "교수이름", EXTRACT(YEAR FROM CURRENT_DATE) - 1900 - SUBSTR(PROFESSOR_SSN,1,2) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = '1';


SELECT SUBSTR(PROFESSOR_NAME, 2) "이름"
FROM TB_PROFESSOR;


SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';


SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, ENTRANCE_DATE
FROM TB_STUDENT
WHERE SUBSTR(EXTRACT(YEAR FROM TB_STUDENT.ENTRANCE_DATE),1,2)  - SUBSTR(STUDENT_SSN,1,2) = '19';






SELECT STUDENT_NAME "이름", STUDENT_ADDRESS "주소"
FROM TB_STUDENT
ORDER BY "이름" ASC;

SELECT STUDENT_NAME "이름", STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY SUBSTR(STUDENT_SSN,1,6) DESC;

SELECT STUDENT_NAME "학생 이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
AND SUBSTR(STUDENT_NO,1,1) = '9'
ORDER BY STUDENT_NAME ASC;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY SUBSTR(PROFESSOR_SSN, 1, 2) ASC;

SELECT STUDENT_NO, TO_CHAR(POINT, 'FM9.00') "학점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC, STUDENT_NO ASC;

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO);

SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CATEGORY = '인문사회'
ORDER BY CLASS_NAME ASC;

SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ROUND(AVG(POINT),1)) "학점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NO = '059'
GROUP BY STUDENT_NO, STUDENT_NAME;

SELECT DEPARTMENT_NAME, STUDENT_NAME, PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT ON (TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO)
WHERE STUDENT_NO ='A313047';

SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2007' AND CLASS_NAME = '인간관계론';

SELECT STUDENT_NAME"학생 이름", NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM (
	SELECT *
	FROM TB_STUDENT
	LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '서반아어학과'
)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
ORDER BY STUDENT_NO ASC;

SELECT STUDENT_NO "학번", STUDENT_NAME "이름", DEPARTMENT_NAME "학과 이름", AVG(POINT)"평점"
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE ABSENCE_YN != 'Y' 
	GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
	HAVING AVG(POINT) >= 4;

SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),2)
FROM (
	SELECT *
	FROM TB_CLASS
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME ='환경조경학과' AND CLASS_TYPE ='전공선택'
)
JOIN TB_GRADE USING (CLASS_NO)
GROUP BY CLASS_NO, CLASS_NAME;

SELECT 이름, 주소
FROM (
	SELECT STUDENT_NAME"이름", STUDENT_ADDRESS"주소"
	FROM TB_STUDENT
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME ='최경희')
);

SELECT *
FROM 
(
	SELECT STUDENT_NO, STUDENT_NAME, AVG(POINT)"평점"
	FROM TB_STUDENT
	JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
	JOIN TB_GRADE USING (STUDENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO, STUDENT_NAME
	ORDER BY 평점 DESC
)
WHERE ROWNUM = 1;


SELECT DEPARTMENT_NAME"계열학과명", ROUND(AVG(POINT),1)"전공 평점", AVG(POINT)
FROM TB_CLASS
LEFT JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = (
	SELECT CATEGORY
	FROM TB_DEPARTMENT
	WHERE DEPARTMENT_NAME = '환경조경학과'
) AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME
ORDER BY DEPARTMENT_NAME ASC;

SELECT *
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

















